### ISSUE TITLE
Add support for handling archive permisions on hardened servers

### ISSUE THREAD

**Issue by ghorsman** [voxpupuli/puppet-jira#77]
Hi,

The module downloads the file as the puppet user (in this case root) and then attempts to untar the module as the jira user. This fails if the server is hardened and restricts permissions on downloaded files. We have to work around this by adding the following heira:

```
system::execs:
    chown_jira_tarball:
        command: /bin/chown -R jira:jira /opt/staging/
        unless: /usr/bin/stat -c "%U:%G" /opt/staging/jira/atlassian-jira-6.4.2.tar.gz | /bin/grep jira:jira
        require: Staging::File[atlassian-jira-6.4.2.tar.gz]
        before: Exec[extract atlassian-jira-6.4.2.tar.gz]
```

You'll note this has to reference the version-specific file so when attempting any upgrade you have to change these names as well.

It would be good if the module handled this itself by explicitly ensuring the archive permision are correct before attempting the extract.

This is also the case for confluence and I'll raise it there as well.
